exports.response = function(req, res) {
  return {
    "code": "0",
    "msg": "OK",
    "resultData": {
      "custList": {
        "pageSize": 10,
        "totalCount": 234,
        "totalPage": 24,
        "pageNo": 0,
        "beginIndex": 0,
        "eleContents": [
          {
            "brok_id": "924944463686",
            "main_pty_mng": "759822502291",
            "brok_org_id": "ZZ323294 ZZ323264 ZZ001041",
            "p_or_o": null,
            "risk_lvl": "704010",
            "asset": null,
            "open_dt": null,
            "user_rights": "817030 817440",
            "mini_fee": null,
            "cust_type": null,
            "id_num": null,
            "telephone": null,
            "relatedLabels": "企业高管 双城属性 创业板客户 沪市私募债投资者 权证账户 价值投资 长期闲置 深港通客户 工人阶级 融资打新客户 基金账户 回购账户 潜在大户 退休养老 沪港通客户 精英白领 乐米版猜涨跌客户 股票客户 布尔事实 新三板客户 大转盘客户 学生党 海外出差 期权软件客户 融资融券客户 布尔模型 理财账户 布尔 测试 转融通客户 优先股专业投资者 债券账户 ",
            "reasonDesc": "",
            "name": null
          },
          {
            "brok_id": "196746929466",
            "main_pty_mng": "951282059322",
            "brok_org_id": "ZZ323294 ZZ323264 ZZ001041",
            "p_or_o": null,
            "risk_lvl": "704030",
            "asset": null,
            "open_dt": null,
            "user_rights": "817030 817440",
            "mini_fee": null,
            "cust_type": null,
            "id_num": null,
            "telephone": null,
            "relatedLabels": "企业高管 双城属性 创业板客户 沪市私募债投资者 权证账户 价值投资 长期闲置 深港通客户 工人阶级 融资打新客户 基金账户 回购账户 潜在大户 退休养老 沪港通客户 精英白领 乐米版猜涨跌客户 股票客户 布尔事实 新三板客户 大转盘客户 学生党 海外出差 期权软件客户 融资融券客户 布尔模型 理财账户 布尔 测试 转融通客户 优先股专业投资者 债券账户 ",
            "reasonDesc": "",
            "name": null
          },
          {
            "brok_id": "678766163280",
            "main_pty_mng": "769760109691",
            "brok_org_id": "ZZ323294 ZZ323264 ZZ001041",
            "p_or_o": null,
            "risk_lvl": "704015",
            "asset": null,
            "open_dt": null,
            "user_rights": "817030 817270 817010",
            "mini_fee": null,
            "cust_type": null,
            "id_num": null,
            "telephone": null,
            "relatedLabels": "企业高管 双城属性 创业板客户 沪市私募债投资者 权证账户 价值投资 长期闲置 深港通客户 工人阶级 融资打新客户 基金账户 回购账户 潜在大户 退休养老 沪港通客户 精英白领 乐米版猜涨跌客户 股票客户 布尔事实 新三板客户 大转盘客户 学生党 海外出差 期权软件客户 融资融券客户 布尔模型 理财账户 布尔 测试 转融通客户 优先股专业投资者 债券账户 ",
            "reasonDesc": "",
            "name": null
          },
          {
            "brok_id": "165597791149",
            "main_pty_mng": "769760109691",
            "brok_org_id": "ZZ323294 ZZ323264 ZZ001041",
            "p_or_o": null,
            "risk_lvl": "704020",
            "asset": null,
            "open_dt": null,
            "user_rights": "817200",
            "mini_fee": null,
            "cust_type": null,
            "id_num": null,
            "telephone": null,
            "relatedLabels": "企业高管 双城属性 创业板客户 沪市私募债投资者 权证账户 价值投资 长期闲置 深港通客户 工人阶级 融资打新客户 基金账户 回购账户 潜在大户 退休养老 沪港通客户 精英白领 乐米版猜涨跌客户 股票客户 布尔事实 新三板客户 大转盘客户 学生党 海外出差 期权软件客户 融资融券客户 布尔模型 理财账户 布尔 测试 转融通客户 优先股专业投资者 债券账户 ",
            "reasonDesc": "",
            "name": null
          },
          {
            "brok_id": "411633993089",
            "main_pty_mng": "865470491502",
            "brok_org_id": "ZZ323294 ZZ323264 ZZ001041",
            "p_or_o": null,
            "risk_lvl": "704040",
            "asset": null,
            "open_dt": null,
            "user_rights": "817030 817440",
            "mini_fee": null,
            "cust_type": null,
            "id_num": null,
            "telephone": null,
            "relatedLabels": "企业高管 双城属性 创业板客户 沪市私募债投资者 权证账户 价值投资 长期闲置 深港通客户 工人阶级 融资打新客户 基金账户 回购账户 潜在大户 退休养老 沪港通客户 精英白领 乐米版猜涨跌客户 股票客户 布尔事实 新三板客户 大转盘客户 学生党 海外出差 期权软件客户 融资融券客户 布尔模型 理财账户 布尔 测试 转融通客户 优先股专业投资者 债券账户 ",
            "reasonDesc": "",
            "name": null
          },
          {
            "brok_id": "393248548799",
            "main_pty_mng": "759822502291",
            "brok_org_id": "ZZ323294 ZZ323264 ZZ001041",
            "p_or_o": null,
            "risk_lvl": "704030",
            "asset": null,
            "open_dt": null,
            "user_rights": "817200",
            "mini_fee": null,
            "cust_type": null,
            "id_num": null,
            "telephone": null,
            "relatedLabels": "企业高管 双城属性 创业板客户 沪市私募债投资者 权证账户 价值投资 长期闲置 深港通客户 工人阶级 融资打新客户 基金账户 回购账户 潜在大户 退休养老 沪港通客户 精英白领 乐米版猜涨跌客户 股票客户 布尔事实 新三板客户 大转盘客户 学生党 海外出差 期权软件客户 融资融券客户 布尔模型 理财账户 布尔 测试 转融通客户 优先股专业投资者 债券账户 ",
            "reasonDesc": "",
            "name": null
          },
          {
            "brok_id": "105996569899",
            "main_pty_mng": "424014323702",
            "brok_org_id": "ZZ323294 ZZ323264 ZZ001041",
            "p_or_o": null,
            "risk_lvl": "704010",
            "asset": null,
            "open_dt": null,
            "user_rights": "817030 817270 817010",
            "mini_fee": null,
            "cust_type": null,
            "id_num": null,
            "telephone": null,
            "relatedLabels": "企业高管 双城属性 创业板客户 沪市私募债投资者 权证账户 价值投资 长期闲置 深港通客户 工人阶级 融资打新客户 基金账户 回购账户 潜在大户 退休养老 沪港通客户 精英白领 乐米版猜涨跌客户 股票客户 布尔事实 新三板客户 大转盘客户 学生党 海外出差 期权软件客户 融资融券客户 布尔模型 理财账户 布尔 测试 转融通客户 优先股专业投资者 债券账户 ",
            "reasonDesc": "",
            "name": null
          },
          {
            "brok_id": "867344002673",
            "main_pty_mng": "876155087592",
            "brok_org_id": "ZZ323294 ZZ323264 ZZ001041",
            "p_or_o": null,
            "risk_lvl": "704030",
            "asset": null,
            "open_dt": null,
            "user_rights": "817030 817270 817010",
            "mini_fee": null,
            "cust_type": null,
            "id_num": null,
            "telephone": null,
            "relatedLabels": "企业高管 双城属性 创业板客户 沪市私募债投资者 权证账户 价值投资 长期闲置 深港通客户 工人阶级 融资打新客户 基金账户 回购账户 潜在大户 退休养老 沪港通客户 精英白领 乐米版猜涨跌客户 股票客户 布尔事实 新三板客户 大转盘客户 学生党 海外出差 期权软件客户 融资融券客户 布尔模型 理财账户 布尔 测试 转融通客户 优先股专业投资者 债券账户 ",
            "reasonDesc": "",
            "name": null
          },
          {
            "brok_id": "449836363274",
            "main_pty_mng": "865470491502",
            "brok_org_id": "ZZ323294 ZZ323264 ZZ001041",
            "p_or_o": null,
            "risk_lvl": "704015",
            "asset": null,
            "open_dt": null,
            "user_rights": "817200",
            "mini_fee": null,
            "cust_type": null,
            "id_num": null,
            "telephone": null,
            "relatedLabels": "企业高管 双城属性 创业板客户 沪市私募债投资者 权证账户 价值投资 长期闲置 深港通客户 工人阶级 融资打新客户 基金账户 回购账户 潜在大户 退休养老 沪港通客户 精英白领 乐米版猜涨跌客户 股票客户 布尔事实 新三板客户 大转盘客户 学生党 海外出差 期权软件客户 融资融券客户 布尔模型 理财账户 布尔 测试 转融通客户 优先股专业投资者 债券账户 ",
            "reasonDesc": "",
            "name": null
          },
          {
            "brok_id": "303557557182",
            "main_pty_mng": "865470491502",
            "brok_org_id": "ZZ323294 ZZ323264 ZZ001041",
            "p_or_o": null,
            "risk_lvl": "704015",
            "asset": null,
            "open_dt": null,
            "user_rights": "817200",
            "mini_fee": null,
            "cust_type": null,
            "id_num": null,
            "telephone": null,
            "relatedLabels": "企业高管 双城属性 创业板客户 沪市私募债投资者 权证账户 价值投资 长期闲置 深港通客户 工人阶级 融资打新客户 基金账户 回购账户 潜在大户 退休养老 沪港通客户 精英白领 乐米版猜涨跌客户 股票客户 布尔事实 新三板客户 大转盘客户 学生党 海外出差 期权软件客户 融资融券客户 布尔模型 理财账户 布尔 测试 转融通客户 优先股专业投资者 债券账户 ",
            "reasonDesc": "",
            "name": null
          }
        ],
        "firstPage": true,
        "lastPage": false,
        "nextPage": 1,
        "prePage": 0
      }
    }
  }
}