exports.response = function (req, res) {
    return {
        'code': '0',
        'msg': 'OK',
        'resultData': {
            'id': '380',
            'action': null,
            'createdBy': '1-OXZ5',
            'createdName': '王华',
            'lastUpdateBy': '1-OXZ5',
            'lastUpdateName': '王华',
            'initiator': '',
            'uuid': '1-A1EQ1D',
            'contractNum': '1-8890235166',
            'contractName': 'LZTEST0905',
            'status': null,
            'type': '合作合约',
            'subType': '合作合约',
            'workflowName': '合作合约',
            'workflowNode': '1111',
            'workflowCode': '123131312321321',
            'divisionId': '1-5XNA',
            'divisionName': '南京长江路证券营业部',
            'contactId': '1-DX-4575',
            'accountId': '',
            'custId': null,
            'custType': null,
            'custName': '1-DX-4575',
            'econNum': '02008520',
            'startDt': '09/05/2017',
            'vailDt': '',
            'endDt': '',
            'context': '111',
            'description': '111',
            'assetAccnt': '',
            'terms': [
                {
                    'key': 1,
                    'termsName': '基金子公司产品分成',
                    'paraName': '基金子公司产品分成比例',
                    'paraVal': '0.5',
                    'divIntegrationId': 'ZZ001041054',
                    'divName': '南京解放路证券营业部',
                    'furturePromotion': '',
                    'preCondition': '',
                    'synBusSys': ''
                },
                {
                    'key': 2,
                    'termsName': '基金子公司产品分成2',
                    'paraName': '基金子公司产品分成比例2',
                    'paraVal': '0.52',
                    'divIntegrationId': 'ZZ0010410542',
                    'divName': '南京解放路证券营业部2',
                    'furturePromotion': '',
                    'preCondition': '',
                    'synBusSys': ''
                },
                {
                    'key': 3,
                    'termsName': '基金子公司产品分成3',
                    'paraName': '基金子公司产品分成比例3',
                    'paraVal': '0.53',
                    'divIntegrationId': 'ZZ0010410543',
                    'divName': '南京解放路证券营业部3',
                    'furturePromotion': '',
                    'preCondition': '',
                    'synBusSys': ''
                },
                {
                    'key': 4,
                    'termsName': '基金子公司产品分成4',
                    'paraName': '基金子公司产品分成比例4',
                    'paraVal': '0.54',
                    'divIntegrationId': 'ZZ0010410544',
                    'divName': '南京解放路证券营业部4',
                    'furturePromotion': '',
                    'preCondition': '',
                    'synBusSys': ''
                },
                {
                    'key': 5,
                    'termsName': '基金子公司产品分成5',
                    'paraName': '基金子公司产品分成比例5',
                    'paraVal': '0.55',
                    'divIntegrationId': 'ZZ0010410545',
                    'divName': '南京解放路证券营业部5',
                    'furturePromotion': '',
                    'preCondition': '',
                    'synBusSys': ''
                }
            ],
        }
    }
}