exports.response = function (req, res) {
    return {
        "code": "0",
        "msg": "OK",
        "resultData": {
            "id": "1-435H8HH",
            "appId": '1',
            "createdBy": '1',
            "createdName": '1',
            "lastUpdateBy": '1',
            "lastUpdateName": '1',
            "approver": '1',
            "approverName": '1',
            "createdDt": '2017/07/08',
            "agreementNum": '1',
            "agreementNum": '1',
            "subType": '1',
            "status":'1',
            "startDt": '2017/07/08',
            "vailDt": '2017/07/08',
            "endDt": '2017/07/08',
            "content": '1',
            "templateId": '1',
            "templateName": '1',
            "multiUsedFlag": '1',
            "levelTenFlag": '1',
            "softBusinessType": '1',
            "softPermission": '1',
            "softAccount": '1',
            "softPassword": '1',
            "workflowName": '1',
            "workflowNode": '1',
            "workflowCode": '1',
            "divisionId": '1',
            "contactId": '1',
            "contactName": '1',
            "accountId": '1',
            "custId": '1',
            "custType": '1',
            "softPermission": {
                "code": '1',
                "value": '1',
            },
            "uuid": '1',
            "attachmentType": '1',
            "attachmentComments": '1',
            "item": [
                {
                    "agrId": '1',
                    "prodCode": '1',
                    "prodName": '1',
                    "prodType": '1',
                    "prodSubType": '1',
                    "riskMatchFlag": '1',
                    "termMatchFlag": '1',
                    "varietyMatchFlag": '1',
                    "confirmType": '1',
                    "price": '1',
                },{
                    "agrId": '1',
                    "prodCode": '1',
                    "prodName": '1',
                    "prodType": '1',
                    "prodSubType": '1',
                    "riskMatchFlag": '1',
                    "termMatchFlag": '1',
                    "varietyMatchFlag": '1',
                    "confirmType": '1',
                    "price": '1',
                },
                {
                    "agrId": '1',
                    "prodCode": '1',
                    "prodName": '1',
                    "prodType": '1',
                    "prodSubType": '1',
                    "riskMatchFlag": '1',
                    "termMatchFlag": '1',
                    "varietyMatchFlag": '1',
                    "confirmType": '1',
                    "price": '1',
                },
                {
                    "agrId": '1',
                    "prodCode": '1',
                    "prodName": '1',
                    "prodType": '1',
                    "prodSubType": '1',
                    "riskMatchFlag": '1',
                    "termMatchFlag": '1',
                    "varietyMatchFlag": '1',
                    "confirmType": '1',
                    "price": '1',
                },
                {
                    "agrId": '1',
                    "prodCode": '1',
                    "prodName": '1',
                    "prodType": '1',
                    "prodSubType": '1',
                    "riskMatchFlag": '1',
                    "termMatchFlag": '1',
                    "varietyMatchFlag": '1',
                    "confirmType": '1',
                    "price": '1',
                },
                {
                    "agrId": '1',
                    "prodCode": '1',
                    "prodName": '1',
                    "prodType": '1',
                    "prodSubType": '1',
                    "riskMatchFlag": '1',
                    "termMatchFlag": '1',
                    "varietyMatchFlag": '1',
                    "confirmType": '1',
                    "price": '1',
                },
                {
                    "agrId": '1',
                    "prodCode": '1',
                    "prodName": '1',
                    "prodType": '1',
                    "prodSubType": '1',
                    "riskMatchFlag": '1',
                    "termMatchFlag": '1',
                    "varietyMatchFlag": '1',
                    "confirmType": '1',
                    "price": '1',
                },
                {
                    "agrId": '1',
                    "prodCode": '1',
                    "prodName": '1',
                    "prodType": '1',
                    "prodSubType": '1',
                    "riskMatchFlag": '1',
                    "termMatchFlag": '1',
                    "varietyMatchFlag": '1',
                    "confirmType": '1',
                    "price": '1',
                },
                {
                    "agrId": '1',
                    "prodCode": '1',
                    "prodName": '1',
                    "prodType": '1',
                    "prodSubType": '1',
                    "riskMatchFlag": '1',
                    "termMatchFlag": '1',
                    "varietyMatchFlag": '1',
                    "confirmType": '1',
                    "price": '1',
                }
            ],
            "terms": [
                {
                    "agrId": '1',
                    "key": "0",
                    "termsName": "T91900",
                    "paraName": "T91901",
                    "paraVal": "0.9",
                    "preCondition": '1',
                    "furturePromotion": '1',
                },
                {
                    "agrId": '1',
                    "key": "0",
                    "termsName": "T91900",
                    "paraName": "T91901",
                    "paraVal": "0.9",
                    "preCondition": '1',
                    "furturePromotion": '1',
                },
                {
                    "agrId": '1',
                    "key": "0",
                    "termsName": "T91900",
                    "paraName": "T91901",
                    "paraVal": "0.9",
                    "preCondition": '1',
                    "furturePromotion": '1',
                },
                {
                    "agrId": '1',
                    "key": "0",
                    "termsName": "T91900",
                    "paraName": "T91901",
                    "paraVal": "0.9",
                    "preCondition": '1',
                    "furturePromotion": '1',
                },
                {
                    "agrId": '1',
                    "key": "0",
                    "termsName": "T91900",
                    "paraName": "T91901",
                    "paraVal": "0.9",
                    "preCondition": '1',
                    "furturePromotion": '1',
                },
                {
                    "agrId": '1',
                    "key": "0",
                    "termsName": "T91900",
                    "paraName": "T91901",
                    "paraVal": "0.9",
                    "preCondition": '1',
                    "furturePromotion": '1',
                },
                {
                    "agrId": '1',
                    "key": "0",
                    "termsName": "T91900",
                    "paraName": "T91901",
                    "paraVal": "0.9",
                    "preCondition": '1',
                    "furturePromotion": '1',
                },
                {
                    "agrId": '1',
                    "key": "0",
                    "termsName": "T91900",
                    "paraName": "T91901",
                    "paraVal": "0.9",
                    "preCondition": '1',
                    "furturePromotion": '1',
                },
            ],
            "cust": [
                {
                    "ituId": '1',
                    "agrId": '1',
                    "subCustType": '1',
                    "perEconNum": '1',
                    "perCustId": '1',
                    "perCustName": '1',
                    "orgEconNum": '1',
                    "orgCustId": '1',
                    "orgCustName": '1',
                    "custStatus": '1',
                    "custComments": '1',
                }
            ]
        }
    }
}
