/*
 * @Author: sunweibin
 * @Date: 2018-12-06 17:33:27
 * @Last Modified by: sunweibin
 * @Last Modified time: 2018-12-10 14:24:42
 * @description 交易流水使用到的通用配置项
 */
import moment from 'moment';

// 交易流水默认查询日期半年
export const DATE_FORMATE_API = 'YYYY-MM-DD';
export const DEFAULT_START_DATE = moment().subtract(6, 'months');
export const DEFAULT_END_DATE = moment().subtract(1, 'day');
export const TODAY = moment().format(DATE_FORMATE_API);

// 交易流水三个表格的滚动props
export const NORMAL_SCROLL = { x: 1700 };
export const CREDIT_SCROLL = { x: 1450 };
export const OPTION_SCROLL = { x: 2020 };
// 交易流水中普通账户流水的columns
export const NORMAL_TRADE_COLUMNS = [
  {
    title: '交易日期',
    dataIndex: 'tradeDate',
    key: 'tradeDate',
    className: 'tradeDate',
    fixed: 'left',
    width: 120,
  },
  {
    title: '产品名称',
    dataIndex: 'productName',
    key: 'productName',
    className: 'productName',
    fixed: 'left',
    width: 140,
  },
  {
    title: '产品代码',
    dataIndex: 'productCode',
    key: 'productCode',
    className: 'productCode',
    fixed: 'left',
    width: 90,
  },
  {
    title: '业务类别',
    dataIndex: 'bussinessType',
    key: 'bussinessType',
    className: 'bussinessType',
    width: 180,
  },
  {
    title: '成交价格',
    dataIndex: 'dealPrice',
    key: 'dealPrice',
    className: 'dealPrice',
    align: 'right',
    isNumber: true,
    width: 130,
  },
  {
    title: '成交数量',
    dataIndex: 'dealNumber',
    key: 'dealNumber',
    className: 'dealNumber',
    align: 'right',
    isAmount: true,
    width: 130,
  },
  {
    title: '成交金额',
    dataIndex: 'dealMoney',
    key: 'dealMoney',
    className: 'dealMoney',
    align: 'right',
    isNumber: true,
    width: 130,
  },
  {
    title: '佣金',
    dataIndex: 'commission',
    key: 'commission',
    className: 'commission',
    align: 'right',
    isNumber: true,
    width: 130,
  },
  {
    title: '净佣金',
    dataIndex: 'realCommission',
    key: 'realCommission',
    className: 'realCommission',
    align: 'right',
    isNumber: true,
    width: 130,
  },
  {
    title: '印花税',
    dataIndex: 'stampTax',
    key: 'stampTax',
    className: 'stampTax',
    align: 'right',
    isNumber: true,
    width: 130,
  },
  {
    title: '风险金',
    dataIndex: 'riskMoney',
    key: 'riskMoney',
    className: 'riskMoney',
    align: 'right',
    isNumber: true,
    width: 130,
  },
  {
    title: '产品类型',
    dataIndex: 'productType',
    key: 'productType',
    className: 'productType',
    width: 100,
  },
  {
    title: '交易渠道',
    dataIndex: 'tradeChannel',
    key: 'tradeChannel',
    className: 'tradeChannel',
    width: 120,
  },
];
// 交易流水中信用账户的columns
export const CREDIT_TRADE_COLUMNS = [
  {
    title: '交易日期',
    dataIndex: 'tradeDate',
    key: 'tradeDate',
    className: 'tradeDate',
    fixed: 'left',
    width: 120,
  },
  {
    title: '产品名称',
    dataIndex: 'productName',
    key: 'productName',
    className: 'productName',
    fixed: 'left',
    width: 140,
  },
  {
    title: '产品代码',
    dataIndex: 'productCode',
    key: 'productCode',
    className: 'productCode',
    fixed: 'left',
    width: 90,
  },
  {
    title: '业务类别',
    dataIndex: 'bussinessType',
    key: 'bussinessType',
    className: 'bussinessType',
    width: 180,
  },
  {
    title: '成交价格',
    dataIndex: 'dealPrice',
    key: 'dealPrice',
    className: 'dealPrice',
    align: 'right',
    isNumber: true,
    width: 130,
  },
  {
    title: '成交数量',
    dataIndex: 'dealNumber',
    key: 'dealNumber',
    className: 'dealNumber',
    align: 'right',
    isAmount: true,
    width: 130,
  },
  {
    title: '成交金额',
    dataIndex: 'dealMoney',
    key: 'dealMoney',
    className: 'dealMoney',
    align: 'right',
    isNumber: true,
    width: 130,
  },
  {
    title: '佣金',
    dataIndex: 'commission',
    key: 'commission',
    className: 'commission',
    align: 'right',
    isNumber: true,
    width: 130,
  },
  {
    title: '净佣金',
    dataIndex: 'realCommission',
    key: 'realCommission',
    className: 'realCommission',
    align: 'right',
    isNumber: true,
    width: 130,
  },
  {
    title: '印花税',
    dataIndex: 'stampTax',
    key: 'stampTax',
    className: 'stampTax',
    align: 'right',
    isNumber: true,
    width: 130,
  },
  {
    title: '交易渠道',
    dataIndex: 'tradeChannel',
    key: 'tradeChannel',
    className: 'tradeChannel',
    width: 120,
  },
];
// 交易流水中期权账户流水的columns
export const OPTION_TRADE_COLUMNS = [
  {
    title: '交易日期',
    dataIndex: 'tradeDate',
    key: 'tradeDate',
    className: 'tradeDate',
    fixed: 'left',
    width: 120,
  },
  {
    title: '期权合约简称',
    dataIndex: 'optionContractName',
    key: 'optionContractName',
    className: 'optionContractName',
    fixed: 'left',
    width: 150,
  },
  {
    title: '期权合约编码',
    dataIndex: 'optionContractCode',
    key: 'optionContractCode',
    className: 'optionContractCode',
    fixed: 'left',
    width: 150,
  },
  {
    title: '业务类别',
    dataIndex: 'bussinessType',
    key: 'bussinessType',
    className: 'bussinessType',
    width: 180,
  },
  {
    title: '成交价格',
    dataIndex: 'dealPrice',
    key: 'dealPrice',
    className: 'dealPrice',
    isNumber: true,
    width: 130,
  },
  {
    title: '成交数量',
    dataIndex: 'dealNumber',
    key: 'dealNumber',
    className: 'dealNumber',
    align: 'right',
    isAmount: true,
    width: 130,
  },
  {
    title: '成交金额',
    dataIndex: 'dealMoney',
    key: 'dealMoney',
    className: 'dealMoney',
    align: 'right',
    isNumber: true,
    width: 130,
  },
  {
    title: '佣金',
    dataIndex: 'commission',
    key: 'commission',
    className: 'commission',
    align: 'right',
    isNumber: true,
    width: 130,
  },
  {
    title: '净佣金',
    dataIndex: 'realCommission',
    key: 'realCommission',
    className: 'realCommission',
    align: 'right',
    isNumber: true,
    width: 130,
  },
  {
    title: '一级经手费',
    dataIndex: 'oneLevelBrokerage',
    key: 'oneLevelBrokerage',
    className: 'oneLevelBrokerage',
    align: 'right',
    isNumber: true,
    width: 130,
  },
  {
    title: '其他费(结算费)',
    dataIndex: 'otherCost',
    key: 'otherCost',
    className: 'otherCost',
    align: 'right',
    isNumber: true,
    width: 130,
  },
  {
    title: '期权种类',
    dataIndex: 'optionCategory',
    key: 'optionCategory',
    className: 'optionCategory',
    width: 120,
  },
  {
    title: '期权持仓类别',
    dataIndex: 'optionPositionsCategory',
    key: 'optionPositionsCategory',
    className: 'optionPositionsCategory',
    width: 120,
  },
  {
    title: '证券代码',
    dataIndex: 'stockCode',
    key: 'stockCode',
    className: 'stockCode',
    width: 90,
  },
  {
    title: '买卖方向',
    dataIndex: 'businessDirection',
    key: 'businessDirection',
    className: 'businessDirection',
    width: 90,
  },
  {
    title: '开平仓方向',
    dataIndex: 'openStorageDirection',
    key: 'openStorageDirection',
    className: 'openStorageDirection',
    width: 90,
  },
];
// 交易流水资金变动columns
export const CAPITAL_CHANGE_COLUMNS = [
  {
    title: '交易日期',
    dataIndex: 'tradeDate',
    key: 'tradeDate',
    className: 'tradeDate',
    width: '14%',
  },
  {
    title: '资金账号',
    dataIndex: 'accountNumber',
    key: 'accountNumber',
    className: 'accountNumber',
    width: '14%',
  },
  {
    title: '币种',
    dataIndex: 'currency',
    key: 'currency',
    className: 'currency',
    width: '14%',
  },
  {
    title: '交易渠道',
    dataIndex: 'tradeChannel',
    key: 'tradeChannel',
    className: 'tradeChannel',
    width: '14%',
  },
  {
    title: '业务标志',
    dataIndex: 'serviceIndication',
    key: 'serviceIndication',
    className: 'serviceIndication',
    width: '15%',
  },
  {
    title: '交易金额(元)',
    dataIndex: 'ammount',
    key: 'ammount',
    align: 'right',
    className: 'ammount',
    isNumber: true,
    width: '14%',
  },
  {
    title: '余额(元)',
    dataIndex: 'balance',
    key: 'balance',
    align: 'right',
    className: 'balance',
    isNumber: true,
    width: '14%',
  },
];
