/**
 * 历史对比折线图mock数据
 */
exports.response = function (req, res) {
  return {
    code: '0',
    msg: 'OK',
    resultData: {
      current: [
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '286196829585.3774',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2017',
            month: '07',
            day: '05',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '286196829585.3774',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2017',
            month: '07',
            day: '06',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '286196829585.3774',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2017',
            month: '07',
            day: '07',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '286196829585.3774',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2017',
            month: '07',
            day: '08',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '286196829585.3774',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2017',
            month: '07',
            day: '09',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '286196829585.3774',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2017',
            month: '07',
            day: '10',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '286196829585.3774',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2017',
            month: '07',
            day: '11',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '286196829585.3774',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2017',
            month: '07',
            day: '12',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '286196829585.3774',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2017',
            month: '07',
            day: '13',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '286196829585.3774',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2017',
            month: '07',
            day: '14',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '286196829585.3774',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2017',
            month: '07',
            day: '15',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '286196829585.3774',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2017',
            month: '07',
            day: '16',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '286196829585.3774',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2017',
            month: '07',
            day: '17',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '286196829585.3774',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2017',
            month: '07',
            day: '18',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '286196829585.3774',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2017',
            month: '07',
            day: '19',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '286196829585.3774',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2017',
            month: '07',
            day: '20',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '286196829585.3774',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2017',
            month: '07',
            day: '21',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '286196829585.3774',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2017',
            month: '07',
            day: '22',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '286196829585.3774',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2017',
            month: '07',
            day: '23',
          },
        },
      ],
      previous: [
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '0',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2016',
            month: '07',
            day: '05',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '0',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2016',
            month: '07',
            day: '06',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '0',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2016',
            month: '07',
            day: '07',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '0',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2016',
            month: '07',
            day: '08',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '0',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2016',
            month: '07',
            day: '09',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '0',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2016',
            month: '07',
            day: '10',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '0',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2016',
            month: '07',
            day: '11',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '0',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2016',
            month: '07',
            day: '12',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '0',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2016',
            month: '07',
            day: '13',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '0',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2016',
            month: '07',
            day: '14',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '0',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2016',
            month: '07',
            day: '15',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '0',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2016',
            month: '07',
            day: '16',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '0',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2016',
            month: '07',
            day: '17',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '0',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2016',
            month: '07',
            day: '18',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '0',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2016',
            month: '07',
            day: '19',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '0',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2016',
            month: '07',
            day: '20',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '0',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2016',
            month: '07',
            day: '21',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '0',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2016',
            month: '07',
            day: '22',
          },
        },
        {
          indicatorMetaDto: {
            key: 'totAset',
            name: '托管总资产',
            value: '0',
            unit: '元',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
          },
          timeModel: {
            year: '2016',
            month: '07',
            day: '23',
          },
        },
      ],
    },
  };
};
