exports.response = function (req, res) {
  return {
    code: '0',
    msg: 'OK',
    resultData: {
        title: '客户数明细',
        id: 'bo-1',
        data: [
          {
            key: 'tgInNum',
            name: '投顾入岗人数',
            value: null,
            unit: '人',
            description: null,
            orgModel: [
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041093',
                level2Name: '南京分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '34',
                children: [
                    {
                        value: '-20',
                        name: '个人',
                    },
                    {
                        value: '20',
                        name: '机构',
                    },
                    {
                        value: '20',
                        name: '组织',
                    },
                    {
                        value: '20',
                        name: '天天发布市值',
                    },
                    {
                        value: '20',
                        name: '流通股市',
                    },
                    {
                        value: '20',
                        name: '限售市值',
                    },
                ],
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041106',
                level2Name: '南通分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '34',
                  children: [
                    {
                        value: '20',
                        name: '个人',
                    },
                    {
                        value: '-1',
                        name: '机构',
                    },
                    {
                        value: '11',
                        name: '组织',
                    },
                    {
                        value: '11',
                        name: '天天发布市值',
                    },
                    {
                        value: '11',
                        name: '流通股市',
                    },
                    {
                        value: '11',
                        name: '限售市值',
                    },
                ],
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323262',
                level2Name: '徐州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '25',
                  children: [
                    {
                        value: '1',
                        name: '个人',
                    },
                    {
                        value: '11',
                        name: '机构',
                    },
                    {
                        value: '-10',
                        name: '组织',
                    },
                    {
                        value: '11',
                        name: '天天发布市值',
                    },
                    {
                        value: '11',
                        name: '流通股市',
                    },
                    {
                        value: '11',
                        name: '限售市值',
                    },
                ],
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323261',
                level2Name: '常州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '15',
                children: [
                    {
                        value: '5',
                        name: '个人',
                    },
                    {
                        value: '5',
                        name: '机构',
                    },
                    {
                        value: '-5',
                        name: '组织',
                    },
                    {
                        value: '11',
                        name: '天天发布市值',
                    },
                    {
                        value: '11',
                        name: '流通股市',
                    },
                    {
                        value: '11',
                        name: '限售市值',
                    },
                ],
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041103',
                level2Name: '苏州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '23',
                children: [
                    {
                        value: '7',
                        name: '个人',
                    },
                    {
                        value: '11',
                        name: '机构',
                    },
                    {
                        value: '5',
                        name: '组织',
                    },
                    {
                        value: '11',
                        name: '天天发布市值',
                    },
                    {
                        value: '11',
                        name: '流通股市',
                    },
                    {
                        value: '11',
                        name: '限售市值',
                    },
                ],
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323269',
                level2Name: '淮安分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '24',
                children: [
                    {
                        value: '23',
                        name: '个人',
                    },
                    {
                        value: '1',
                        name: '机构',
                    },
                    {
                        value: '0',
                        name: '组织',
                    },
                    {
                        value: '11',
                        name: '天天发布市值',
                    },
                    {
                        value: '11',
                        name: '流通股市',
                    },
                    {
                        value: '11',
                        name: '限售市值',
                    },
                ],
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323263',
                level2Name: '无锡分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
                  children: [
                    {
                        value: '0',
                        name: '个人',
                    },
                    {
                        value: '0',
                        name: '机构',
                    },
                    {
                        value: '11',
                        name: '组织',
                    },
                    {
                        value: '11',
                        name: '天天发布市值',
                    },
                    {
                        value: '11',
                        name: '流通股市',
                    },
                    {
                        value: '11',
                        name: '限售市值',
                    },
                ],
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323266',
                level2Name: '扬州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
                  children: [
                    {
                        value: '0',
                        name: '个人',
                    },
                    {
                        value: '0',
                        name: '机构',
                    },
                    {
                        value: '0',
                        name: '组织',
                    },
                    {
                        value: '11',
                        name: '天天发布市值',
                    },
                    {
                        value: '11',
                        name: '流通股市',
                    },
                    {
                        value: '11',
                        name: '限售市值',
                    },
                ],
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041116',
                level2Name: '辽宁分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '22',
                 children: [
                    {
                        value: '11',
                        name: '个人',
                    },
                    {
                        value: '4',
                        name: '机构',
                    },
                    {
                        value: '7',
                        name: '组织',
                    },
                    {
                        value: '11',
                        name: '天天发布市值',
                    },
                    {
                        value: '11',
                        name: '流通股市',
                    },
                    {
                        value: '11',
                        name: '限售市值',
                    },
                ],
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323275',
                level2Name: '云南分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
                 children: [
                    {
                        value: '0',
                        name: '个人',
                    },
                    {
                        value: '0',
                        name: '机构',
                    },
                    {
                        value: '0',
                        name: '组织',
                    },
                    {
                        value: '11',
                        name: '天天发布市值',
                    },
                    {
                        value: '11',
                        name: '流通股市',
                    },
                    {
                        value: '11',
                        name: '限售市值',
                    },
                ],
              },
            ],
          },
          {
            key: 'currSignCustNum',
            name: '签约客户数',
            value: null,
            unit: '户',
            description: '当前签约客户数',
            orgModel: [
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041116',
                level2Name: '辽宁分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041107',
                level2Name: '上海分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323272',
                level2Name: '镇江分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323271',
                level2Name: '泰州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041166',
                level2Name: '深圳分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041111',
                level2Name: '湖北分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323275',
                level2Name: '云南分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323269',
                level2Name: '淮安分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323273',
                level2Name: '江阴分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041109',
                level2Name: '天津分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
            ],
          },
          {
            key: 'currSignCustAset',
            name: '签约总资产',
            value: null,
            unit: '元',
            description: null,
            orgModel: [
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041116',
                level2Name: '辽宁分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041107',
                level2Name: '上海分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323272',
                level2Name: '镇江分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323271',
                level2Name: '泰州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041166',
                level2Name: '深圳分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041111',
                level2Name: '湖北分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323275',
                level2Name: '云南分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323269',
                level2Name: '淮安分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323273',
                level2Name: '江阴分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041109',
                level2Name: '天津分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
            ],
          },
        ],
    },
  };
}
