/**
 * 历史对比排名柱状图数据
 */
exports.response = function (req, res) {
  return {
    code: '0',
    msg: 'OK',
    resultData: {
      historyCardRecordVo: {
        current_page: '1',
        total_num: '18',
        data: {
          indiModel: {
            key: 'totTranInt',
            name: '产品净手续费收入',
            value: null,
            unit: '元',
            description: '统计期内【公募+紫金（剔除天天发940018、940028、940038）+OTC+私募】产品（场外认购+场外申购+场内认购）产生手续费净收入',
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: 'Y',
            parentKey: null,
            parentName: null,
            children: null,
            isAggressive: null,
          },
          orgModel: [
            {
              level1Id: 'ZZ001041',
              level1Name: '经纪及财富管理部',
              level2Id: 'ZZ323265',
              level2Name: '福建分公司',
              level3Id: null,
              level3Name: null,
              level4Id: null,
              level4Name: null,
              value: '8054.52',
              rank: '1',
              rank_current: '1',
              rank_contrast: '2',
              rand_change: '1',
              changeRate: null,
              indiModelList: [
                {
                  key: 'kfTranInt',
                  name: '公募',
                  value: '8054.52',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
                {
                  key: 'taTranInt',
                  name: '紫金',
                  value: '0',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
                {
                  key: 'smTranInt',
                  name: '私募',
                  value: '0',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
              ],
            },
            {
              level1Id: 'ZZ001041',
              level1Name: '经纪及财富管理部',
              level2Id: 'ZZ323265',
              level2Name: '福建分公司',
              level3Id: null,
              level3Name: null,
              level4Id: null,
              level4Name: null,
              value: '8054.52',
              rank: '2',
              rank_current: '2',
              rank_contrast: '1',
              rand_change: '-1',
              changeRate: null,
              indiModelList: [
                {
                  key: 'kfTranInt',
                  name: '公募',
                  value: '8054.52',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
                {
                  key: 'taTranInt',
                  name: '紫金',
                  value: '0',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
                {
                  key: 'smTranInt',
                  name: '私募',
                  value: '0',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
              ],
            },
            {
              level1Id: 'ZZ001041',
              level1Name: '经纪及财富管理部',
              level2Id: 'ZZ323265',
              level2Name: '福建分公司',
              level3Id: null,
              level3Name: null,
              level4Id: null,
              level4Name: null,
              value: '8054.52',
              rank: '3',
              rank_current: '3',
              rank_contrast: '2',
              rand_change: '1',
              changeRate: null,
              indiModelList: [
                {
                  key: 'kfTranInt',
                  name: '公募',
                  value: '8054.52',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
                {
                  key: 'taTranInt',
                  name: '紫金',
                  value: '0',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
                {
                  key: 'smTranInt',
                  name: '私募',
                  value: '0',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
              ],
            },
            {
              level1Id: 'ZZ001041',
              level1Name: '经纪及财富管理部',
              level2Id: 'ZZ323265',
              level2Name: '福建分公司',
              level3Id: null,
              level3Name: null,
              level4Id: null,
              level4Name: null,
              value: '8054.52',
              rank: '4',
              rank_current: '4',
              rank_contrast: '2',
              rand_change: '1',
              changeRate: null,
              indiModelList: [
                {
                  key: 'kfTranInt',
                  name: '公募',
                  value: '8054.52',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
                {
                  key: 'taTranInt',
                  name: '紫金',
                  value: '0',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
                {
                  key: 'smTranInt',
                  name: '私募',
                  value: '0',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
              ],
            },
            {
              level1Id: 'ZZ001041',
              level1Name: '经纪及财富管理部',
              level2Id: 'ZZ323265',
              level2Name: '福建分公司',
              level3Id: null,
              level3Name: null,
              level4Id: null,
              level4Name: null,
              value: '8054.52',
              rank: '5',
              rank_current: '5',
              rank_contrast: '2',
              rand_change: '1',
              changeRate: null,
              indiModelList: [
                {
                  key: 'kfTranInt',
                  name: '公募',
                  value: '8054.52',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
                {
                  key: 'taTranInt',
                  name: '紫金',
                  value: '0',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
                {
                  key: 'smTranInt',
                  name: '私募',
                  value: '0',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
              ],
            },
            {
              level1Id: 'ZZ001041',
              level1Name: '经纪及财富管理部',
              level2Id: 'ZZ001041111',
              level2Name: '湖北分公司',
              level3Id: null,
              level3Name: null,
              level4Id: null,
              level4Name: null,
              value: '4103.68',
              rank: '6',
              rank_current: '6',
              rank_contrast: '2',
              rand_change: '1',
              changeRate: null,
              indiModelList: [
                {
                  key: 'kfTranInt',
                  name: '公募',
                  value: '2603.68',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
                {
                  key: 'taTranInt',
                  name: '紫金',
                  value: '1500',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
                {
                  key: 'smTranInt',
                  name: '私募',
                  value: '0',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
              ],
            },
            {
              level1Id: 'ZZ001041',
              level1Name: '经纪及财富管理部',
              level2Id: 'ZZ001041111',
              level2Name: '湖北分公司',
              level3Id: null,
              level3Name: null,
              level4Id: null,
              level4Name: null,
              value: '4103.68',
              rank: '7',
              rank_current: '7',
              rank_contrast: '2',
              rand_change: '1',
              changeRate: null,
              indiModelList: [
                {
                  key: 'kfTranInt',
                  name: '公募',
                  value: '2603.68',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
                {
                  key: 'taTranInt',
                  name: '紫金',
                  value: '1500',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
                {
                  key: 'smTranInt',
                  name: '私募',
                  value: '0',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
              ],
            },
            {
              level1Id: 'ZZ001041',
              level1Name: '经纪及财富管理部',
              level2Id: 'ZZ001041111',
              level2Name: '湖北分公司',
              level3Id: null,
              level3Name: null,
              level4Id: null,
              level4Name: null,
              value: '4103.68',
              rank: '8',
              rank_current: '8',
              rank_contrast: '2',
              rand_change: '1',
              changeRate: null,
              indiModelList: [
                {
                  key: 'kfTranInt',
                  name: '公募',
                  value: '2603.68',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
                {
                  key: 'taTranInt',
                  name: '紫金',
                  value: '1500',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
                {
                  key: 'smTranInt',
                  name: '私募',
                  value: '0',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
              ],
            },
            {
              level1Id: 'ZZ001041',
              level1Name: '经纪及财富管理部',
              level2Id: 'ZZ001041111',
              level2Name: '湖北分公司',
              level3Id: null,
              level3Name: null,
              level4Id: null,
              level4Name: null,
              value: '4103.68',
              rank: '9',
              rank_current: '9',
              rank_contrast: '2',
              rand_change: '1',
              changeRate: null,
              indiModelList: [
                {
                  key: 'kfTranInt',
                  name: '公募',
                  value: '2603.68',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
                {
                  key: 'taTranInt',
                  name: '紫金',
                  value: '1500',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
                {
                  key: 'smTranInt',
                  name: '私募',
                  value: '0',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
              ],
            },
            {
              level1Id: 'ZZ001041',
              level1Name: '经纪及财富管理部',
              level2Id: 'ZZ001041111',
              level2Name: '湖北分公司',
              level3Id: null,
              level3Name: null,
              level4Id: null,
              level4Name: null,
              value: '4103.68',
              rank: '10',
              rank_current: '10',
              rank_contrast: '2',
              rand_change: '1',
              changeRate: null,
              indiModelList: [
                {
                  key: 'kfTranInt',
                  name: '公募',
                  value: '2603.68',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
                {
                  key: 'taTranInt',
                  name: '紫金',
                  value: '1500',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
                {
                  key: 'smTranInt',
                  name: '私募',
                  value: '0',
                  unit: '元',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: null,
                  parentName: '产品净手续费收入',
                  children: null,
                  isAggressive: null,
                },
              ],
            },
          ],
        },
      },
    },
  };
};
