exports.response = function (req, res) {
  return {
    code: '0',
    msg: 'OK',
    resultData: [
      {
        name: '客户数明细',
        id: 'bo-1',
        key: '1-bo-1',
        indexData: [
          {
            key: 'tgInNum',
            name: '投顾入岗人数',
            value: null,
            unit: '人',
            description: null,
            orgModel: [
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041093',
                level2Name: '南京分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: [
                    {
                        value: '11',
                        legend: 'a',
                    },
                    {
                        value: '11',
                        legend: 'b',
                    },
                    {
                        value: '11',
                        legend: 'c',
                    },
                ],
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041106',
                level2Name: '南通分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                  value: [
                    {
                        value: '20',
                        legend: 'a',
                    },
                    {
                        value: '1',
                        legend: 'b',
                    },
                    {
                        value: '11',
                        legend: 'c',
                    },
                ],
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323262',
                level2Name: '徐州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                  value: [
                    {
                        value: '1',
                        legend: 'a',
                    },
                    {
                        value: '11',
                        legend: 'b',
                    },
                    {
                        value: '10',
                        legend: 'c',
                    },
                ],
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323261',
                level2Name: '常州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: [
                    {
                        value: '5',
                        legend: 'a',
                    },
                    {
                        value: '5',
                        legend: 'b',
                    },
                    {
                        value: '5',
                        legend: 'c',
                    },
                ],
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041103',
                level2Name: '苏州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: [
                    {
                        value: '7',
                        legend: 'a',
                    },
                    {
                        value: '11',
                        legend: 'b',
                    },
                    {
                        value: '5',
                        legend: 'c',
                    },
                ],
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323269',
                level2Name: '淮安分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                  value: [
                    {
                        value: '23',
                        legend: 'a',
                    },
                    {
                        value: '1',
                        legend: 'b',
                    },
                    {
                        value: '0',
                        legend: 'c',
                    },
                ],
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323263',
                level2Name: '无锡分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                  value: [
                    {
                        value: '0',
                        legend: 'a',
                    },
                    {
                        value: '0',
                        legend: 'b',
                    },
                    {
                        value: '11',
                        legend: 'c',
                    },
                ],
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323266',
                level2Name: '扬州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                  value: [
                    {
                        value: '0',
                        legend: 'a',
                    },
                    {
                        value: '0',
                        legend: 'b',
                    },
                    {
                        value: '0',
                        legend: 'c',
                    },
                ],
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041116',
                level2Name: '辽宁分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                 value: [
                    {
                        value: '11',
                        legend: 'a',
                    },
                    {
                        value: '4',
                        legend: 'b',
                    },
                    {
                        value: '7',
                        legend: 'c',
                    },
                ],
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323275',
                level2Name: '云南分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                 value: [
                    {
                        value: '0',
                        legend: 'a',
                    },
                    {
                        value: '0',
                        legend: 'b',
                    },
                    {
                        value: '0',
                        legend: 'c',
                    },
                ],
              },
            ],
          },
          {
            key: 'currSignCustNum',
            name: '签约客户数',
            value: null,
            unit: '户',
            description: '当前签约客户数',
            orgModel: [
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041116',
                level2Name: '辽宁分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041107',
                level2Name: '上海分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323272',
                level2Name: '镇江分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323271',
                level2Name: '泰州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041166',
                level2Name: '深圳分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041111',
                level2Name: '湖北分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323275',
                level2Name: '云南分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323269',
                level2Name: '淮安分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323273',
                level2Name: '江阴分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041109',
                level2Name: '天津分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
            ],
          },
          {
            key: 'currSignCustAset',
            name: '签约总资产',
            value: null,
            unit: '元',
            description: null,
            orgModel: [
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041116',
                level2Name: '辽宁分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041107',
                level2Name: '上海分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323272',
                level2Name: '镇江分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323271',
                level2Name: '泰州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041166',
                level2Name: '深圳分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041111',
                level2Name: '湖北分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323275',
                level2Name: '云南分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323269',
                level2Name: '淮安分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323273',
                level2Name: '江阴分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041109',
                level2Name: '天津分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
            ],
          },
        ],
      },
      {
        name: '资产明细',
        id: 'bo-2',
        key: '1-bo-2',
        indexData: [
          {
            key: 'totAset',
            name: '托管总资产',
            value: null,
            unit: '元',
            description: null,
            orgModel: [
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041093',
                level2Name: '南京分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '30823561050.9399',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041106',
                level2Name: '南通分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '18975704474.5988',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323261',
                level2Name: '常州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '17119633598.7411',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041103',
                level2Name: '苏州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '9807271870.8073',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323262',
                level2Name: '徐州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '8097646290.9418',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323269',
                level2Name: '淮安分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '2797165818.3158',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323263',
                level2Name: '无锡分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '1749486560.3092',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323266',
                level2Name: '扬州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '826188165.3055',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323265',
                level2Name: '福建分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '84470.63',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041116',
                level2Name: '辽宁分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
            ],
          },
          {
            key: 'gjAvgPercent',
            name: '股基平均佣金率',
            value: null,
            unit: '‰',
            description: null,
            orgModel: [
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323263',
                level2Name: '无锡分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323270',
                level2Name: '盐城分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323288',
                level2Name: '江西分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323264',
                level2Name: '河南分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041116',
                level2Name: '辽宁分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323267',
                level2Name: '安徽分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041108',
                level2Name: '北京分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323265',
                level2Name: '福建分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041093',
                level2Name: '南京分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323268',
                level2Name: '山东分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
            ],
          },
          {
            key: 'purRake',
            name: '净佣金收入',
            value: null,
            unit: '元',
            description: null,
            orgModel: [
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041093',
                level2Name: '南京分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '214833.1669',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041106',
                level2Name: '南通分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '204256.7077',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323261',
                level2Name: '常州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '180771.1641',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323262',
                level2Name: '徐州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '115093.19',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041103',
                level2Name: '苏州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '98981.3747',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323269',
                level2Name: '淮安分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '46171.55',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323263',
                level2Name: '无锡分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '23124.14',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323266',
                level2Name: '扬州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '17107.41',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323265',
                level2Name: '福建分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '48.89',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041116',
                level2Name: '辽宁分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
            ],
          },
        ],
      },
      {
        name: '交易量明细',
        id: 'bo-3',
        key: '1-bo-3',
        indexData: [
          {
            key: 'purInteIncome',
            name: '净利息收入',
            value: null,
            unit: '元',
            description: null,
            orgModel: [
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041116',
                level2Name: '辽宁分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041107',
                level2Name: '上海分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323272',
                level2Name: '镇江分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323271',
                level2Name: '泰州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041166',
                level2Name: '深圳分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041111',
                level2Name: '湖北分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323275',
                level2Name: '云南分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323269',
                level2Name: '淮安分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323273',
                level2Name: '江阴分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041109',
                level2Name: '天津分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
            ],
          },
          {
            key: 'prdtPurFee',
            name: '产品净手续费收入',
            value: null,
            unit: '元',
            description: null,
            orgModel: [
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323261',
                level2Name: '常州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '40062.61',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041106',
                level2Name: '南通分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '277.98',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041093',
                level2Name: '南京分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '156.63',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323262',
                level2Name: '徐州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '13.35',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323269',
                level2Name: '淮安分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '5.96',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323266',
                level2Name: '扬州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '2.98',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041116',
                level2Name: '辽宁分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323275',
                level2Name: '云南分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323273',
                level2Name: '江阴分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041109',
                level2Name: '天津分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
            ],
          },
          {
            key: 'feeConfigPercent',
            name: '资产配置覆盖率',
            value: null,
            unit: '%',
            description: null,
            orgModel: [
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323265',
                level2Name: '福建分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '1',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323262',
                level2Name: '徐州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.4493150684931506849315068493150684931507',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323269',
                level2Name: '淮安分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.4463849109325881942018861334264757247642',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041106',
                level2Name: '南通分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.4315520864605223656559591714199939957971',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041093',
                level2Name: '南京分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.4117727960390592765781873194883784898913',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323261',
                level2Name: '常州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.2869569136470164052641067243555074815215',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041103',
                level2Name: '苏州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.2779590357078122167844843211890520210259',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323263',
                level2Name: '无锡分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.2473142345568487018800358102059086839749',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323266',
                level2Name: '扬州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.1375413987921293590492889148646015975063',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041116',
                level2Name: '辽宁分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
            ],
          },
        ],
      },
      {
        name: '产品明细',
        id: 'bo-4',
        key: '1-bo-4',
        indexData: [
          {
            key: 'infoCompPercent',
            name: '高净值客户信息完善率',
            value: null,
            unit: '%',
            description: null,
            orgModel: [
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323266',
                level2Name: '扬州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.9725471698113207547169811320754716981132',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323262',
                level2Name: '徐州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.9669299850070384473276801827248104504912',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323263',
                level2Name: '无锡分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.9516617495711835334476843910806174957118',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041106',
                level2Name: '南通分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.9455701503439040720676851908211090145475',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323261',
                level2Name: '常州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.9410271403935507677478142343984155552712',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323269',
                level2Name: '淮安分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.9246108949416342412451361867704280155643',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041093',
                level2Name: '南京分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.9203159798126168035399440897797485594878',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041103',
                level2Name: '苏州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.8996993578517221249270286047869235259778',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041116',
                level2Name: '辽宁分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041111',
                level2Name: '湖北分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
            ],
          },
          {
            key: 'motCompletePercent',
            name: 'MOT任务完成率',
            value: null,
            unit: '%',
            description: null,
            orgModel: [
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323263',
                level2Name: '无锡分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323270',
                level2Name: '盐城分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323288',
                level2Name: '江西分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323264',
                level2Name: '河南分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041116',
                level2Name: '辽宁分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323267',
                level2Name: '安徽分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041108',
                level2Name: '北京分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323265',
                level2Name: '福建分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041093',
                level2Name: '南京分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323268',
                level2Name: '山东分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
            ],
          },
          {
            key: 'serviceCompPercent',
            name: '服务覆盖率',
            value: null,
            unit: '%',
            description: null,
            orgModel: [
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041093',
                level2Name: '南京分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.757048549030394718745702104249759317838',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323269',
                level2Name: '淮安分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.6447782046804051694027244149493538246594',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323262',
                level2Name: '徐州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.6276002029426686960933536276002029426687',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323261',
                level2Name: '常州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.4609248242293131422390481341265548945376',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041103',
                level2Name: '苏州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.4433568968642378104042051839767989849556',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323266',
                level2Name: '扬州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.3960646795246444574323007987531657899864',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041106',
                level2Name: '南通分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.3872710897628339837886520564395076553588',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323263',
                level2Name: '无锡分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.2372426141450313339301700984780662488809',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041116',
                level2Name: '辽宁分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323275',
                level2Name: '云南分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
            ],
          },
        ],
      },
      {
        name: '开通业务明细',
        id: 'bo-5',
        key: '1-bo-5',
        indexData: [
          {
            key: 'currSignCustNum',
            name: '签约客户数',
            value: null,
            unit: '户',
            description: '当前签约客户数',
            orgModel: [
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041116',
                level2Name: '辽宁分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041107',
                level2Name: '上海分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323272',
                level2Name: '镇江分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323271',
                level2Name: '泰州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041166',
                level2Name: '深圳分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041111',
                level2Name: '湖北分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323275',
                level2Name: '云南分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323269',
                level2Name: '淮安分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323273',
                level2Name: '江阴分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041109',
                level2Name: '天津分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
            ],
          },
          {
            key: 'currSignCustAset',
            name: '签约总资产',
            value: null,
            unit: '元',
            description: null,
            orgModel: [
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041116',
                level2Name: '辽宁分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041107',
                level2Name: '上海分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323272',
                level2Name: '镇江分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323271',
                level2Name: '泰州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041166',
                level2Name: '深圳分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041111',
                level2Name: '湖北分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323275',
                level2Name: '云南分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323269',
                level2Name: '淮安分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323273',
                level2Name: '江阴分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041109',
                level2Name: '天津分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
            ],
          },
          {
            key: 'totAset',
            name: '托管总资产',
            value: null,
            unit: '元',
            description: null,
            orgModel: [
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041093',
                level2Name: '南京分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '30823561050.9399',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041106',
                level2Name: '南通分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '18975704474.5988',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323261',
                level2Name: '常州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '17119633598.7411',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041103',
                level2Name: '苏州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '9807271870.8073',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323262',
                level2Name: '徐州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '8097646290.9418',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323269',
                level2Name: '淮安分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '2797165818.3158',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323263',
                level2Name: '无锡分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '1749486560.3092',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323266',
                level2Name: '扬州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '826188165.3055',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323265',
                level2Name: '福建分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '84470.63',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041116',
                level2Name: '辽宁分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
            ],
          },
        ],
      },
      {
        name: '净收入明细',
        id: 'bo-6',
        key: '1-bo-6',
        indexData: [
          {
            key: 'purInteIncome',
            name: '净利息收入',
            value: null,
            unit: '元',
            description: null,
            orgModel: [
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041116',
                level2Name: '辽宁分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041107',
                level2Name: '上海分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323272',
                level2Name: '镇江分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323271',
                level2Name: '泰州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041166',
                level2Name: '深圳分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041111',
                level2Name: '湖北分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323275',
                level2Name: '云南分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323269',
                level2Name: '淮安分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323273',
                level2Name: '江阴分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041109',
                level2Name: '天津分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
            ],
          },
          {
            key: 'prdtPurFee',
            name: '产品净手续费收入',
            value: null,
            unit: '元',
            description: null,
            orgModel: [
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323261',
                level2Name: '常州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '40062.61',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041106',
                level2Name: '南通分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '277.98',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041093',
                level2Name: '南京分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '156.63',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323262',
                level2Name: '徐州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '13.35',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323269',
                level2Name: '淮安分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '5.96',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323266',
                level2Name: '扬州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '2.98',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041116',
                level2Name: '辽宁分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323275',
                level2Name: '云南分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323273',
                level2Name: '江阴分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041109',
                level2Name: '天津分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
            ],
          },
          {
            key: 'feeConfigPercent',
            name: '资产配置覆盖率',
            value: null,
            unit: '%',
            description: null,
            orgModel: [
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323265',
                level2Name: '福建分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '1',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323262',
                level2Name: '徐州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.4493150684931506849315068493150684931507',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323269',
                level2Name: '淮安分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.4463849109325881942018861334264757247642',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041106',
                level2Name: '南通分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.4315520864605223656559591714199939957971',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041093',
                level2Name: '南京分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.4117727960390592765781873194883784898913',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323261',
                level2Name: '常州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.2869569136470164052641067243555074815215',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041103',
                level2Name: '苏州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.2779590357078122167844843211890520210259',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323263',
                level2Name: '无锡分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.2473142345568487018800358102059086839749',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323266',
                level2Name: '扬州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.1375413987921293590492889148646015975063',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041116',
                level2Name: '辽宁分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
            ],
          },
        ],
      },
      {
        name: '高净值客户服务明细',
        id: 'bo-7',
        key: '1-bo-7',
        indexData: [
          {
            key: 'purInteIncome',
            name: '净利息收入',
            value: null,
            unit: '元',
            description: null,
            orgModel: [
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041116',
                level2Name: '辽宁分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041107',
                level2Name: '上海分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323272',
                level2Name: '镇江分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323271',
                level2Name: '泰州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041166',
                level2Name: '深圳分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041111',
                level2Name: '湖北分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323275',
                level2Name: '云南分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323269',
                level2Name: '淮安分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323273',
                level2Name: '江阴分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041109',
                level2Name: '天津分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
            ],
          },
          {
            key: 'prdtPurFee',
            name: '产品净手续费收入',
            value: null,
            unit: '元',
            description: null,
            orgModel: [
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323261',
                level2Name: '常州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '40062.61',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041106',
                level2Name: '南通分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '277.98',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041093',
                level2Name: '南京分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '156.63',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323262',
                level2Name: '徐州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '13.35',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323269',
                level2Name: '淮安分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '5.96',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323266',
                level2Name: '扬州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '2.98',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041116',
                level2Name: '辽宁分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323275',
                level2Name: '云南分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323273',
                level2Name: '江阴分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041109',
                level2Name: '天津分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
            ],
          },
          {
            key: 'feeConfigPercent',
            name: '资产配置覆盖率',
            value: null,
            unit: '%',
            description: null,
            orgModel: [
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323265',
                level2Name: '福建分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '1',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323262',
                level2Name: '徐州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.4493150684931506849315068493150684931507',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323269',
                level2Name: '淮安分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.4463849109325881942018861334264757247642',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041106',
                level2Name: '南通分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.4315520864605223656559591714199939957971',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041093',
                level2Name: '南京分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.4117727960390592765781873194883784898913',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323261',
                level2Name: '常州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.2869569136470164052641067243555074815215',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041103',
                level2Name: '苏州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.2779590357078122167844843211890520210259',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323263',
                level2Name: '无锡分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.2473142345568487018800358102059086839749',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ323266',
                level2Name: '扬州分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0.1375413987921293590492889148646015975063',
              },
              {
                level1Id: 'ZZ001041',
                level1Name: '经纪业务总部',
                level2Id: 'ZZ001041116',
                level2Name: '辽宁分公司',
                level3Id: null,
                level3Name: null,
                level4Id: null,
                level4Name: null,
                value: '0',
              },
            ],
          },
        ],
      },
    ],
  };
}
