/**
 * @description 查询某一个看板的信息
 */

exports.response = function (req, res) {
  return {
    code: '0',
    msg: 'OK',
    resultData: {
      id: 11,
      name: '看板postman1',
      boardType: 'TYPE_JYYJ',
      boardTypeDesc: '经营业绩',
      boardStatusDesc: '发布',
      description: '看板postman1',
      ownerOrgId: 'ZZ001041',
      boardStatus: 'RELEASE',
      createTime: '2017-06-27 10:15:03',
      updateTime: '2017-06-27 12:23:53',
      pubTime: null,
      isEditable: 'Y',
      orgModel: null,
      summury: [
        {
          key: 'pNewCustNum',
          name: '个人新开客户数',
          value: null,
          unit: '户',
          description: null,
          categoryKey: null,
          isBelongsSummury: null,
          hasChildren: null,
          parentKey: 'newCustNum',
          parentName: null,
          children: null,
        },
        {
          key: 'tgInNum',
          name: '投顾入岗人数',
          value: null,
          unit: '人',
          description: null,
          categoryKey: null,
          isBelongsSummury: null,
          hasChildren: null,
          parentKey: null,
          parentName: null,
          children: null,
        },
      ],
      detail: [
        {
          indicatorCategoryDto: {
            categoryKey: 'custAmountDetail',
            categoryName: '客户数明细',
            parentCateKey: 'managementIndicator',
            level: '2',
            remark: null,
          },
          detailIndicators: [
            {
              key: 'effCustNum',
              name: '有效客户数',
              value: null,
              unit: '户',
              description: null,
              categoryKey: null,
              isBelongsSummury: null,
              hasChildren: null,
              parentKey: null,
              parentName: null,
              children: null,
            },
            {
              key: 'InminorCustNum',
              name: '高净值客户数',
              value: null,
              unit: '户',
              description: null,
              categoryKey: null,
              isBelongsSummury: null,
              hasChildren: null,
              parentKey: null,
              parentName: null,
              children: null,
            },
            {
              key: 'newCustNum',
              name: '新开客户数',
              value: null,
              unit: '户',
              description: '我认为这个指标就是三个子指标的和',
              categoryKey: null,
              isBelongsSummury: null,
              hasChildren: 'Y',
              parentKey: null,
              parentName: null,
              children: [
                {
                  key: 'pNewCustNum',
                  name: '个人新开客户数',
                  value: null,
                  unit: '户',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: 'newCustNum',
                  parentName: null,
                  children: null,
                },
                {
                  key: 'oNewCustNum',
                  name: '机构新开客户数',
                  value: null,
                  unit: '户',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: 'newCustNum',
                  parentName: null,
                  children: null,
                },
                {
                  key: 'oNewPrdtCustNum',
                  name: '产品新开客户数',
                  value: null,
                  unit: '户',
                  description: null,
                  categoryKey: null,
                  isBelongsSummury: null,
                  hasChildren: null,
                  parentKey: 'newCustNum',
                  parentName: null,
                  children: null,
                },
              ],
            },
            {
              key: 'hignLoseCustPercent',
              name: '高净值客户流失率',
              value: null,
              unit: '%',
              description: '这个指标不知取哪个字段',
              categoryKey: null,
              isBelongsSummury: null,
              hasChildren: null,
              parentKey: null,
              parentName: null,
              children: null,
            },
          ],
        },
        {
          indicatorCategoryDto: {
            categoryKey: 'newBusinessDetail',
            categoryName: '新开通业务明细',
            parentCateKey: 'managementIndicator',
            level: '2',
            remark: null,
          },
          detailIndicators: [
            {
              key: 'rzrqBusi',
              name: '融资融券',
              value: null,
              unit: '户',
              description: null,
              categoryKey: null,
              isBelongsSummury: null,
              hasChildren: null,
              parentKey: null,
              parentName: null,
              children: null,
            },
          ],
        },
      ],
    },
  };
};
