/**
 * 指标库
 */

exports.response = function (req, res) {
  return {
    code: '0',
    msg: 'OK',
    resultData: [
      {
        indicatorCategoryDto: {
          categoryKey: 'custAmountDetail',
          categoryName: '客户数明细',
          parentCateKey: 'managementIndicator',
          level: '2',
          remark: null,
        },
        detailIndicators: [
          {
            key: 'totCustNum',
            name: '总客户数',
            value: null,
            unit: '户',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
            isChoosed: 'N',
          },
          {
            key: 'effCustNum',
            name: '有效客户数',
            value: null,
            unit: '户',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
            isChoosed: 'Y',
          },
          {
            key: 'InminorCustNum',
            name: '高净值客户数',
            value: null,
            unit: '户',
            description: null,
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
            isChoosed: 'Y',
          },
          {
            key: 'newCustNum',
            name: '新开客户数',
            value: null,
            unit: '户',
            description: '我认为这个指标就是三个子指标的和',
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: 'Y',
            parentKey: null,
            parentName: null,
            children: [
              {
                key: 'pNewCustNum',
                name: '个人新开客户数',
                value: null,
                unit: '户',
                description: null,
                categoryKey: null,
                isBelongsSummury: null,
                hasChildren: null,
                parentKey: 'newCustNum',
                parentName: null,
                children: null,
                isChoosed: 'Y',
              },
              {
                key: 'oNewCustNum',
                name: '机构新开客户数',
                value: null,
                unit: '户',
                description: null,
                categoryKey: null,
                isBelongsSummury: null,
                hasChildren: null,
                parentKey: 'newCustNum',
                parentName: null,
                children: null,
                isChoosed: 'Y',
              },
              {
                key: 'oNewPrdtCustNum',
                name: '产品新开客户数',
                value: null,
                unit: '户',
                description: null,
                categoryKey: null,
                isBelongsSummury: null,
                hasChildren: null,
                parentKey: 'newCustNum',
                parentName: null,
                children: null,
                isChoosed: 'Y',
              },
            ],
            isChoosed: 'Y',
          },
          {
            key: 'hignLoseCustPercent',
            name: '高净值客户流失率',
            value: null,
            unit: '%',
            description: '这个指标不知取哪个字段',
            categoryKey: null,
            isBelongsSummury: null,
            hasChildren: null,
            parentKey: null,
            parentName: null,
            children: null,
            isChoosed: 'Y',
          },
        ],
      },
    ],
  };
};
