exports.response = function (req, res) {
  return {
    "code": "0",
    "msg": "OK",
    "resultData": {
       "key": "b0-1",
       "name": "客户数明细", 
      "data": {
        "indicatorSummuryRecordDtos": [
          {
            "id": "ZZ001041120",
            "name": "四川分公司",
            "level": "2",
            "orgModel": {
                "level1Id": "ZZ001041",
                "level1Name": "测试-经纪业务总部",
                "level2Id": "ZZ001041093",
                "level2Name": "测试-南京分公司",
                "level3Id": "ZZ1093892023",
                "level3Name": "测试-解放路营业部",
                "level4Id": "ZZ10000999",
                "level4Name": "测试-人员",
                "value": "34"
            },
            "indicatorDataList": [
              {
                "key": "tgInNum",
                "name": "投顾入岗人数",
                "value": "0",
                "unit": "人",
                "description": null
              }, {
                "key": "currSignCustNum",
                "name": "签约客户数",
                "value": "0",
                "unit": "户",
                "description": "当前签约客户数"
              }, {
                "key": "currSignCustAset",
                "name": "签约总资产",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "totAset",
                "name": "托管总资产",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "gjAvgPercent",
                "name": "股基平均佣金率",
                "value": "0",
                "unit": "‰",
                "description": null
              }, {
                "key": "purRake",
                "name": "净佣金收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "purInteIncome",
                "name": "净利息收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "prdtPurFee",
                "name": "产品净手续费收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "feeConfigPercent",
                "name": "资产配置覆盖率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "infoCompPercent",
                "name": "高净值客户信息完善率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "motCompletePercent",
                "name": "MOT任务完成率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "serviceCompPercent",
                "name": "服务覆盖率",
                "value": "0",
                "unit": "%",
                "description": null
              }
            ]
          }, {
            "id": "ZZ001041106",
            "name": "营业部",
            "level": "3",
            "orgModel": {
                "level1Id": "ZZ001041",
                "level1Name": "测试-经纪业务总部",
                "level2Id": "ZZ001041093",
                "level2Name": "测试-南京分公司",
                "level3Id": "ZZ1093892023",
                "level3Name": "测试-解放路营业部",
                "level4Id": "ZZ10000999",
                "level4Name": "测试-人员",
                "value": "34"
            },
            "indicatorDataList": [
              {
                "key": "tgInNum",
                "name": "投顾入岗人数",
                "value": "34",
                "unit": "人",
                "description": null
              }, {
                "key": "currSignCustNum",
                "name": "签约客户数",
                "value": "0",
                "unit": "户",
                "description": "当前签约客户数"
              }, {
                "key": "currSignCustAset",
                "name": "签约总资产",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "totAset",
                "name": "托管总资产",
                "value": "18975704474.5988",
                "unit": "元",
                "description": null
              }, {
                "key": "gjAvgPercent",
                "name": "股基平均佣金率",
                "value": "0",
                "unit": "‰",
                "description": null
              }, {
                "key": "purRake",
                "name": "净佣金收入",
                "value": "204256.7077",
                "unit": "元",
                "description": null
              }, {
                "key": "purInteIncome",
                "name": "净利息收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "prdtPurFee",
                "name": "产品净手续费收入",
                "value": "277.98",
                "unit": "元",
                "description": null
              }, {
                "key": "feeConfigPercent",
                "name": "资产配置覆盖率",
                "value": "0.4315520864605223656559591714199939957971",
                "unit": "%",
                "description": null
              }, {
                "key": "infoCompPercent",
                "name": "高净值客户信息完善率",
                "value": "0.9455701503439040720676851908211090145475",
                "unit": "%",
                "description": null
              }, {
                "key": "motCompletePercent",
                "name": "MOT任务完成率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "serviceCompPercent",
                "name": "服务覆盖率",
                "value": "0.3872710897628339837886520564395076553588",
                "unit": "%",
                "description": null
              }
            ]
          }, {
            "id": "ZZ323270",
            "name": "投顾",
            "level": "4",
            "orgModel": {
                "level1Id": "ZZ001041",
                "level1Name": "测试-经纪业务总部",
                "level2Id": "ZZ001041093",
                "level2Name": "测试-南京分公司",
                "level3Id": "ZZ1093892023",
                "level3Name": "测试-解放路营业部",
                "level4Id": "ZZ10000999",
                "level4Name": "测试-人员",
                "value": "34"
            },
            "indicatorDataList": [
              {
                "key": "tgInNum",
                "name": "投顾入岗人数",
                "value": "0",
                "unit": "人",
                "description": null
              }, {
                "key": "currSignCustNum",
                "name": "签约客户数",
                "value": "0",
                "unit": "户",
                "description": "当前签约客户数"
              }, {
                "key": "currSignCustAset",
                "name": "签约总资产",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "totAset",
                "name": "托管总资产",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "gjAvgPercent",
                "name": "股基平均佣金率",
                "value": "0",
                "unit": "‰",
                "description": null
              }, {
                "key": "purRake",
                "name": "净佣金收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "purInteIncome",
                "name": "净利息收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "prdtPurFee",
                "name": "产品净手续费收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "feeConfigPercent",
                "name": "资产配置覆盖率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "infoCompPercent",
                "name": "高净值客户信息完善率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "motCompletePercent",
                "name": "MOT任务完成率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "serviceCompPercent",
                "name": "服务覆盖率",
                "value": "0",
                "unit": "%",
                "description": null
              }
            ]
          }, {
            "id": "ZZ323274",
            "name": "湖南分公司",
            "level": "2",
            "indicatorDataList": [
              {
                "key": "tgInNum",
                "name": "投顾入岗人数",
                "value": "0",
                "unit": "人",
                "description": null
              }, {
                "key": "currSignCustNum",
                "name": "签约客户数",
                "value": "0",
                "unit": "户",
                "description": "当前签约客户数"
              }, {
                "key": "currSignCustAset",
                "name": "签约总资产",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "totAset",
                "name": "托管总资产",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "gjAvgPercent",
                "name": "股基平均佣金率",
                "value": "0",
                "unit": "‰",
                "description": null
              }, {
                "key": "purRake",
                "name": "净佣金收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "purInteIncome",
                "name": "净利息收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "prdtPurFee",
                "name": "产品净手续费收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "feeConfigPercent",
                "name": "资产配置覆盖率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "infoCompPercent",
                "name": "高净值客户信息完善率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "motCompletePercent",
                "name": "MOT任务完成率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "serviceCompPercent",
                "name": "服务覆盖率",
                "value": "0",
                "unit": "%",
                "description": null
              }
            ]
          }, {
            "id": "ZZ001041107",
            "name": "上海分公司",
            "level": "2",
            "indicatorDataList": [
              {
                "key": "tgInNum",
                "name": "投顾入岗人数",
                "value": "0",
                "unit": "人",
                "description": null
              }, {
                "key": "currSignCustNum",
                "name": "签约客户数",
                "value": "0",
                "unit": "户",
                "description": "当前签约客户数"
              }, {
                "key": "currSignCustAset",
                "name": "签约总资产",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "totAset",
                "name": "托管总资产",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "gjAvgPercent",
                "name": "股基平均佣金率",
                "value": "0",
                "unit": "‰",
                "description": null
              }, {
                "key": "purRake",
                "name": "净佣金收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "purInteIncome",
                "name": "净利息收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "prdtPurFee",
                "name": "产品净手续费收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "feeConfigPercent",
                "name": "资产配置覆盖率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "infoCompPercent",
                "name": "高净值客户信息完善率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "motCompletePercent",
                "name": "MOT任务完成率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "serviceCompPercent",
                "name": "服务覆盖率",
                "value": "0",
                "unit": "%",
                "description": null
              }
            ]
          }, {
            "id": "ZZ001041109",
            "name": "天津分公司",
            "level": "2",
            "indicatorDataList": [
              {
                "key": "tgInNum",
                "name": "投顾入岗人数",
                "value": "0",
                "unit": "人",
                "description": null
              }, {
                "key": "currSignCustNum",
                "name": "签约客户数",
                "value": "0",
                "unit": "户",
                "description": "当前签约客户数"
              }, {
                "key": "currSignCustAset",
                "name": "签约总资产",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "totAset",
                "name": "托管总资产",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "gjAvgPercent",
                "name": "股基平均佣金率",
                "value": "0",
                "unit": "‰",
                "description": null
              }, {
                "key": "purRake",
                "name": "净佣金收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "purInteIncome",
                "name": "净利息收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "prdtPurFee",
                "name": "产品净手续费收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "feeConfigPercent",
                "name": "资产配置覆盖率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "infoCompPercent",
                "name": "高净值客户信息完善率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "motCompletePercent",
                "name": "MOT任务完成率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "serviceCompPercent",
                "name": "服务覆盖率",
                "value": "0",
                "unit": "%",
                "description": null
              }
            ]
          }, {
            "id": "ZZ001041116",
            "name": "辽宁分公司",
            "level": "2",
            "indicatorDataList": [
              {
                "key": "tgInNum",
                "name": "投顾入岗人数",
                "value": "0",
                "unit": "人",
                "description": null
              }, {
                "key": "currSignCustNum",
                "name": "签约客户数",
                "value": "0",
                "unit": "户",
                "description": "当前签约客户数"
              }, {
                "key": "currSignCustAset",
                "name": "签约总资产",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "totAset",
                "name": "托管总资产",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "gjAvgPercent",
                "name": "股基平均佣金率",
                "value": "0",
                "unit": "‰",
                "description": null
              }, {
                "key": "purRake",
                "name": "净佣金收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "purInteIncome",
                "name": "净利息收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "prdtPurFee",
                "name": "产品净手续费收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "feeConfigPercent",
                "name": "资产配置覆盖率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "infoCompPercent",
                "name": "高净值客户信息完善率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "motCompletePercent",
                "name": "MOT任务完成率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "serviceCompPercent",
                "name": "服务覆盖率",
                "value": "0",
                "unit": "%",
                "description": null
              }
            ]
          }, {
            "id": "ZZ323268",
            "name": "山东分公司",
            "level": "2",
            "indicatorDataList": [
              {
                "key": "tgInNum",
                "name": "投顾入岗人数",
                "value": "0",
                "unit": "人",
                "description": null
              }, {
                "key": "currSignCustNum",
                "name": "签约客户数",
                "value": "0",
                "unit": "户",
                "description": "当前签约客户数"
              }, {
                "key": "currSignCustAset",
                "name": "签约总资产",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "totAset",
                "name": "托管总资产",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "gjAvgPercent",
                "name": "股基平均佣金率",
                "value": "0",
                "unit": "‰",
                "description": null
              }, {
                "key": "purRake",
                "name": "净佣金收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "purInteIncome",
                "name": "净利息收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "prdtPurFee",
                "name": "产品净手续费收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "feeConfigPercent",
                "name": "资产配置覆盖率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "infoCompPercent",
                "name": "高净值客户信息完善率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "motCompletePercent",
                "name": "MOT任务完成率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "serviceCompPercent",
                "name": "服务覆盖率",
                "value": "0",
                "unit": "%",
                "description": null
              }
            ]
          }, {
            "id": "ZZ323264",
            "name": "河南分公司",
            "level": "2",
            "indicatorDataList": [
              {
                "key": "tgInNum",
                "name": "投顾入岗人数",
                "value": "0",
                "unit": "人",
                "description": null
              }, {
                "key": "currSignCustNum",
                "name": "签约客户数",
                "value": "0",
                "unit": "户",
                "description": "当前签约客户数"
              }, {
                "key": "currSignCustAset",
                "name": "签约总资产",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "totAset",
                "name": "托管总资产",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "gjAvgPercent",
                "name": "股基平均佣金率",
                "value": "0",
                "unit": "‰",
                "description": null
              }, {
                "key": "purRake",
                "name": "净佣金收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "purInteIncome",
                "name": "净利息收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "prdtPurFee",
                "name": "产品净手续费收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "feeConfigPercent",
                "name": "资产配置覆盖率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "infoCompPercent",
                "name": "高净值客户信息完善率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "motCompletePercent",
                "name": "MOT任务完成率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "serviceCompPercent",
                "name": "服务覆盖率",
                "value": "0",
                "unit": "%",
                "description": null
              }
            ]
          }, {
            "id": "ZZ323273",
            "name": "江阴分公司",
            "level": "2",
            "indicatorDataList": [
              {
                "key": "tgInNum",
                "name": "投顾入岗人数",
                "value": "0",
                "unit": "人",
                "description": null
              }, {
                "key": "currSignCustNum",
                "name": "签约客户数",
                "value": "0",
                "unit": "户",
                "description": "当前签约客户数"
              }, {
                "key": "currSignCustAset",
                "name": "签约总资产",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "totAset",
                "name": "托管总资产",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "gjAvgPercent",
                "name": "股基平均佣金率",
                "value": "0",
                "unit": "‰",
                "description": null
              }, {
                "key": "purRake",
                "name": "净佣金收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "purInteIncome",
                "name": "净利息收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "prdtPurFee",
                "name": "产品净手续费收入",
                "value": "0",
                "unit": "元",
                "description": null
              }, {
                "key": "feeConfigPercent",
                "name": "资产配置覆盖率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "infoCompPercent",
                "name": "高净值客户信息完善率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "motCompletePercent",
                "name": "MOT任务完成率",
                "value": "0",
                "unit": "%",
                "description": null
              }, {
                "key": "serviceCompPercent",
                "name": "服务覆盖率",
                "value": "0",
                "unit": "%",
                "description": null
              }
            ]
          }
        ],
        "titleList": [
          {
            "key": "tgInNum",
            "name": "投顾入岗人数",
            "value": null,
            "unit": "人",
            "description": null
          }, {
            "key": "currSignCustNum",
            "name": "签约客户数",
            "value": null,
            "unit": "户",
            "description": "当前签约客户数"
          }, {
            "key": "currSignCustAset",
            "name": "签约总资产",
            "value": null,
            "unit": "元",
            "description": null
          }, {
            "key": "totAset",
            "name": "托管总资产",
            "value": null,
            "unit": "元",
            "description": null
          }, {
            "key": "gjAvgPercent",
            "name": "股基平均佣金率",
            "value": null,
            "unit": "‰",
            "description": null
          }, {
            "key": "purRake",
            "name": "净佣金收入",
            "value": null,
            "unit": "元",
            "description": null
          }, {
            "key": "purInteIncome",
            "name": "净利息收入",
            "value": null,
            "unit": "元",
            "description": null
          }, {
            "key": "prdtPurFee",
            "name": "产品净手续费收入",
            "value": null,
            "unit": "元",
            "description": null
          }, {
            "key": "feeConfigPercent",
            "name": "资产配置覆盖率",
            "value": null,
            "unit": "%",
            "description": null
          }, {
            "key": "infoCompPercent",
            "name": "高净值客户信息完善率",
            "value": null,
            "unit": "%",
            "description": null
          }, {
            "key": "motCompletePercent",
            "name": "MOT任务完成率",
            "value": null,
            "unit": "%",
            "description": null
          }, {
            "key": "serviceCompPercent",
            "name": "服务覆盖率",
            "value": null,
            "unit": "%",
            "description": null
          }
        ],
        "totalCnt": 30,
        "pageSize": 10,
        "curPageNum": 1,
        "totalPageNum": 3
      }
    }
  }
}