exports.response = function (req, res) {
  return {
    "code": "0",
    "msg": "OK",
    "resultData": {
      "page": {
        "pageSize": 10,
        "curPageNum": 1,
        "totalPageNum": 1,
        "totalRecordNum": 18
      },
      "listData": [
        {
          type: 'problem',
          code: '1232112',
          status: '解决中',
          description: '王企鹅无群二无群二无群二无群多无群无群无群若无群付群无群若付无群付无群若群无人',
          manager: '赵云龙',
          userName: '王强',
          userDepartment: '南京市长江路营业厅',
          date: '2017-02-23',
        },
        {
          type: 'suggestion',
          code: '334',
          status: '关闭',
          description: '王企鹅无群二无群二无群二无群多无群无群无群若无群付群无群若付无群付无群若群无人',
          manager: '赵云龙',
          userName: '王强',
          userDepartment: '南京市长江路营业厅',
          date: '2017-02-23',
        },
        {
          type: 'problem',
          code: '1232112',
          status: '解决中',
          description: '王企鹅无群二无群二无群二无群多无群无群无群若无群付群无群若付无群付无群若群无人',
          manager: '赵云龙',
          userName: '王强',
          userDepartment: '南京市长江路营业厅',
          date: '2017-02-23',
        },
        {
          type: 'problem',
          code: '1232112',
          status: '解决中',
          description: '王企鹅无群二无群二无群二无群多无群无群无群若无群付群无群若付无群付无群若群无人',
          manager: '赵云龙',
          userName: '王强',
          userDepartment: '南京市长江路营业厅',
          date: '2017-02-23',
        },
        {
          type: 'problem',
          code: '1232112',
          status: '解决中',
          description: '王企鹅无群二无群二无群二无群多无群无群无群若无群付群无群若付无群付无群若群无人',
          manager: '赵云龙',
          userName: '王强',
          userDepartment: '南京市长江路营业厅',
          date: '2017-02-23',
        },
        {
          type: 'problem',
          code: '1232112',
          status: '解决中',
          description: '王企鹅无群二无群二无群二无群多无群无群无群若无群付群无群若付无群付无群若群无人',
          manager: '赵云龙',
          userName: '王强',
          userDepartment: '南京市长江路营业厅',
          date: '2017-02-23',
        },
        {
          type: 'problem',
          code: '1232112',
          status: '解决中',
          description: '王企鹅无群二无群二无群二无群多无群无群无群若无群付群无群若付无群付无群若群无人',
          manager: '赵云龙',
          userName: '王强',
          userDepartment: '南京市长江路营业厅',
          date: '2017-02-23',
        },
        {
          type: 'problem',
          code: '1232112',
          status: '解决中',
          description: '王企鹅无群二无群二无群二无群多无群无群无群若无群付群无群若付无群付无群若群无人',
          manager: '赵云龙',
          userName: '王强',
          userDepartment: '南京市长江路营业厅',
          date: '2017-02-23',
        },
        {
          type: 'problem',
          code: '1232112',
          status: '解决中',
          description: '王企鹅无群二无群二无群二无群多无群无群无群若无群付群无群若付无群付无群若群无人',
          manager: '赵云龙',
          userName: '王强',
          userDepartment: '南京市长江路营业厅',
          date: '2017-02-23',
        },
        {
          type: 'problem',
          code: '1232112',
          status: '解决中',
          description: '王企鹅无群二无群二无群二无群多无群无群无群若无群付群无群若付无群付无群若群无人',
          manager: '赵云龙',
          userName: '王强',
          userDepartment: '南京市长江路营业厅',
          date: '2017-02-23',
        },
        {
          type: 'problem',
          code: '1232112',
          status: '解决中',
          description: '王企鹅无群二无群二无群二无群多无群无群无群若无群付群无群若付无群付无群若群无人',
          manager: '赵云龙',
          userName: '王强',
          userDepartment: '南京市长江路营业厅',
          date: '2017-02-23',
        },
        {
          type: 'problem',
          code: '1232112',
          status: '解决中',
          description: '王企鹅无群二无群二无群二无群多无群无群无群若无群付群无群若付无群付无群若群无人',
          manager: '赵云龙',
          userName: '王强',
          userDepartment: '南京市长江路营业厅',
          date: '2017-02-23',
        },
        {
          type: 'problem',
          code: '1232112',
          status: '解决中',
          description: '王企鹅无群二无群二无群二无群多无群无群无群若无群付群无群若付无群付无群若群无人',
          manager: '赵云龙',
          userName: '王强',
          userDepartment: '南京市长江路营业厅',
          date: '2017-02-23',
        },
        {
          type: 'problem',
          code: '1232112',
          status: '解决中',
          description: '王企鹅无群二无群二无群二无群多无群无群无群若无群付群无群若付无群付无群若群无人',
          manager: '赵云龙',
          userName: '王强',
          userDepartment: '南京市长江路营业厅',
          date: '2017-02-23',
        },
        {
          type: 'problem',
          code: '1232112',
          status: '解决中',
          description: '王企鹅无群二无群二无群二无群多无群无群无群若无群付群无群若付无群付无群若群无人',
          manager: '赵云龙',
          userName: '王强',
          userDepartment: '南京市长江路营业厅',
          date: '2017-02-23',
        },
        {
          type: 'problem',
          code: '1232112',
          status: '解决中',
          description: '王企鹅无群二无群二无群二无群多无群无群无群若无群付群无群若付无群付无群若群无人',
          manager: '赵云龙',
          userName: '王强',
          userDepartment: '南京市长江路营业厅',
          date: '2017-02-23',
        },
        {
          type: 'problem',
          code: '1232112',
          status: '解决中',
          description: '王企鹅无群二无群二无群二无群多无群无群无群若无群付群无群若付无群付无群若群无人',
          manager: '赵云龙',
          userName: '王强',
          userDepartment: '南京市长江路营业厅',
          date: '2017-02-23',
        },
        {
          type: 'problem',
          code: '1232112',
          status: '解决中',
          description: '王企鹅无群二无群二无群二无群多无群无群无群若无群付群无群若付无群付无群若群无人',
          manager: '赵云龙',
          userName: '王强',
          userDepartment: '南京市长江路营业厅',
          date: '2017-02-23',
        },
      ],
    }
  };
}